title: "Angular実践入門チュートリアル"
summary: |-
  このチュートリアルでは、簡単なTodoアプリの作成を通してフロントエンドフレームワークAngularを使った基本的な開発を体験することができます。

  初心者の方でも習得できる難易度に設定しつつ、UIフレームワークの導入やFirebaseを使ったデータ永続化といった実践的な内容までカバーしました。これを一通りやれば、応用してさらに複雑なアプリの開発に進んでいけると思います。

  また、初心者向けのチュートリアルにありがちな「なんとなく真似して書いたら動いたけど、本質的なところはよく分からなかった」といった感想に終始してしまわないよう、「なぜそうなるのか」を丁寧に解説することを心がけています。

  自分でも有料級の内容だと思ってますが（笑）、今のところすべて無料で公開しています。
  ぜひチャレンジしてみてください！

topics: [angular, firebase, firestore, javascript, typescript]
published: true
price: 0 # 有料の場合200〜5000
chapters:
  - "1"
  - "2"
  - "3"
  - "4"
allow_override: true
